### PR TITLE
👷🏻‍♂️ New Test Suite

### LINKED ISSUE #7: Build out test suite
Integration and unit tests. Integration tests are pretty tricky for this kind of project but we should definitely figure out a way to implement them.

### PR DESCRIPTION
**Pull request by reaganmcf**
Closes #7

## Todo

- [x] Create example projects for each mode
- [x] Add new tests

### CODE REVIEW

**Comment by reaganmcf** [comment]
Looks like there are really niche edge cases where multiple tests can detect file changes in a different order depending on the scheduler. It sucks but we have to run them all serialized.

**Comment by reaganmcf** [comment]
The CI that is failing is the old one that we aren't even using, and it's a system dependency issue not a tests issue

**Comment by reaganmcf** [comment]
@alayshahh review this when you get a chance, its ~~over 500~~ almost 700 lines so I don't wanna just merge to master until we are sure

**Review by alayshahh — APPROVED** [review]
Looks good!

**Pull request merged**
